#!/bin/sh

#SBATCH --account=NEDQC
#SBATCH --job-name=Opt18
#SBATCH --partition=bdwall
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=30
#SBATCH --error=error18.error
#SBATCH --mail-user=imondragonshem@anl.gov
#SBATCH --time=6-00:00:00

srun --exclusive -N1 -n1 ./Opt_18_Py.sh