#!/bin/sh

#SBATCH --account=NEDQC
#SBATCH --job-name=vbs
#SBATCH --partition=bdwall
#SBATCH --ntasks=10
#SBATCH --cpus-per-task=3
#SBATCH --error=errortest.error
#SBATCH --mail-user=imondragonshem@anl.gov
#SBATCH --time=6-00:00:00

# Load the default version of GNU parallel.
module load parallel


# This specifies the options used to run srun. The "-N1 -n1" options are
# used to allocates a single core to each task.
srun="srun --exclusive -N1 -n1"

# This specifies the options used to run GNU parallel:
#
#   --delay of 0.2 prevents overloading the controlling node.
#
#   -j is the number of tasks run simultaneously.
#
#   The combination of --joblog and --resume create a task log that
#   can be used to monitor progress.
#
parallel="parallel --delay 0.2 -j $SLURM_NTASKS --joblog runtask.log --resume"

# Run a script, runtask.sh, using GNU parallel and srun. Parallel
# will run the runtask script for the numbers 1 through 128. To
# illustrate, the first job will run like this:
#
#   srun --exclusive -N1 -n1 ./runtask.sh arg1:1 > runtask.1
#
$parallel "$srun ./vbs_Py.sh {1} > runtask.sh.{1}" ::: 12 14 16 18 20 22 24 26 28 30